#!/bin/bash

# Auto-Build Environment Setup
# Spec: 004 - Add Tooltip Component with UI Integration
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec 004: Tooltip Component"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start on port $port${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready on port $port${NC}"
}

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo -e "${YELLOW}Installing frontend dependencies...${NC}"
cd frontend && npm install
cd ..

# ============================================
# START SERVICES
# ============================================

echo ""
echo -e "${YELLOW}Starting frontend dev server...${NC}"
cd frontend && npm run dev &
wait_for_service 5173 "Frontend (Vite)"

echo ""
echo -e "${YELLOW}Starting Storybook...${NC}"
cd frontend && npm run storybook &
wait_for_service 6006 "Storybook"

cd ..

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend:  http://copilot.localhost:5173"
echo "  Storybook: http://copilot.localhost:6006"
echo ""
echo "This spec is frontend-only. No backend services required."
echo ""
echo "Quick commands:"
echo "  cd frontend && CI=1 npx vitest run --project=unit   # Run unit tests"
echo "  cd frontend && npx tsc -b --noEmit                  # Type check"
echo "  cd frontend && npx eslint src/                      # Lint"
echo "  cd frontend && npx prettier --check src/            # Format check"
echo ""
